services:
  vdr:
    build: .
    container_name: vdr-ibtikarya
    restart: unless-stopped
    ports:
      - "3000:4028"
    environment:
      - VITE_NEXTCLOUD_URL=https://ibtikarya.sa
      - NODE_ENV=production
      - VITE_DEV_USERNAME=eslam
      - VITE_DEV_APP_PASSWORD=W2PxR-D39RL-gXGBx-ZKmMF-aEM3W
      - VITE_ADMIN_USERNAME=admin
      - VITE_ADMIN_PASSWORD=E$!l@m65as
      - VITE_DEFAULT_USER=eslam
      - VITE_MOCK_MODE=false
      - VITE_FALLBACK_TO_MOCK=true
      - VITE_CACHE_ENABLED=true
      - VITE_CACHE_TTL=300000
      - VITE_LOG_LEVEL=debug
      - VITE_RETRY_ATTEMPTS=3
      - VITE_REQUEST_TIMEOUT=30000
    volumes:
      - vdr_data:/app
    networks:
      - nextcloud-aio

volumes:
  vdr_data:

networks:
  nextcloud-aio:
    external: true

